#!/bin/bash

mkdir -p $HOME/.config
mkdir -p $HOME/.config/lazygit

git clone --depth 1 https://github.com/crayonwow/configs.git
git clone --depth 1 https://github.com/crayonwow/astronvim_v4.git $HOME/.config/nvim
git clone --single-branch --depth 1 https://github.com/gpakosz/.tmux.git
git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1

mkdir tmp_delta
cd tmp_delta
curl -L https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-aarch64-unknown-linux-gnu.tar.gz > file.tar.gz
sudo tar -xzf file.tar.gz
sudo mv delta-0.18.2-aarch64-unknown-linux-gnu/delta /usr/local/bin
cd -
sudo rm -r tmp_delta

curl -fsSL https://apt.cli.rs/pubkey.asc | sudo tee -a /usr/share/keyrings/rust-tools.asc
curl -fsSL https://apt.cli.rs/rust-tools.list | sudo tee /etc/apt/sources.list.d/rust-tools.list
sudo apt update
sudo apt install zoxide

cp configs/.zshrc $HOME
cp configs/lazygit.yml $HOME/.config/lazygit/config.yml
ln -s -f .tmux/.tmux.conf $HOME/.tmux.conf
cp configs/.tmux.conf.local $HOME
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
